Enforce Python version 3 requirement

diff --git a/examples/biased-coin-flip/run-python-example.sh.in b/examples/biased-coin-flip/run-python-example.sh.in
--- a/examples/biased-coin-flip/run-python-example.sh.in
+++ b/examples/biased-coin-flip/run-python-example.sh.in
@@ -1,6 +1,14 @@
 #!/bin/bash
 set -euo pipefail
 
+if [ "@PYTHONINTERP_FOUND@" != "TRUE" ]
+then
+    echo "Cannot run Python example because Python interpreter was not found"
+    exit 1
+fi
+
+python=@PYTHON_EXECUTABLE@
+
 # Run ABC rejection
 echo "Running ABC rejection"
 "@PROJECT_BINARY_DIR@/src/pakman" serial rejection \
@@ -8,8 +16,8 @@ echo "Running ABC rejection"
     --number-accept=10 \
     --epsilon=0 \
     --parameter-names=p \
-    --simulator="python simulator.py heads.txt" \
-    --prior-sampler="python prior-sampler.py 0 1"
+    --simulator="$python simulator.py heads.txt" \
+    --prior-sampler="$python prior-sampler.py 0 1"
 
 # Run ABC SMC
 echo
@@ -19,11 +27,11 @@ echo "Running ABC SMC"
     --population-size=10 \
     --epsilons=2,1,0 \
     --parameter-names=p \
-    --simulator="python simulator.py heads.txt" \
-    --prior-sampler="python prior-sampler.py 0 1" \
-    --perturber="python perturber.py 0.1" \
-    --prior-pdf="python prior-pdf.py 0 1" \
-    --perturbation-pdf="python perturbation-pdf.py 0.1" \
+    --simulator="$python simulator.py heads.txt" \
+    --prior-sampler="$python prior-sampler.py 0 1" \
+    --perturber="$python perturber.py 0.1" \
+    --prior-pdf="$python prior-pdf.py 0 1" \
+    --perturbation-pdf="$python perturbation-pdf.py 0.1" \
 
 # If given argument, read argument as number of parameters to accept and run
 # ABC rejection and ABC SMC using MPI Master
@@ -43,14 +51,14 @@ echo "Running ABC rejection with number-accept=$number_accept"
     --number-accept=$number_accept \
     --epsilon=0 \
     --parameter-names=p \
-    --simulator="python simulator.py heads.txt" \
-    --prior-sampler="python prior-sampler.py 0 1" \
+    --simulator="$python simulator.py heads.txt" \
+    --prior-sampler="$python prior-sampler.py 0 1" \
     > abc-rejection-python.out
 
 echo "Results saved in abc-rejection-python.out"
 
 # Create histogram
-python plot-histogram.py \
+$python plot-histogram.py \
     5 20 --epsilon 0 --inputfile abc-rejection-python.out \
     --bboxtight --outputfile abc-rejection-python-histogram.png
 
@@ -64,17 +72,17 @@ echo "Running ABC SMC with population-size=$number_accept"
     --population-size=$number_accept \
     --epsilons=2,1,0 \
     --parameter-names=p \
-    --simulator="python simulator.py heads.txt" \
-    --prior-sampler="python prior-sampler.py 0 1" \
-    --perturber="python perturber.py 0.1" \
-    --prior-pdf="python prior-pdf.py 0 1" \
-    --perturbation-pdf="python perturbation-pdf.py 0.1" \
+    --simulator="$python simulator.py heads.txt" \
+    --prior-sampler="$python prior-sampler.py 0 1" \
+    --perturber="$python perturber.py 0.1" \
+    --prior-pdf="$python prior-pdf.py 0 1" \
+    --perturbation-pdf="$python perturbation-pdf.py 0.1" \
     > abc-smc-python.out
 
 echo "Results saved in abc-smc-python.out"
 
 # Create histogram
-python plot-histogram.py \
+$python plot-histogram.py \
     5 20 --epsilon 0 --inputfile abc-smc-python.out \
     --bboxtight --outputfile abc-smc-python-histogram.png
 
